apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-api
spec:
  type: NodePort # Exposes the service on each Node's IP at a static port (the NodePort). change to load balancer if running in cloud
  selector:
    app: kubernetes-demo-api
  ports:
    - protocol: TCP
      port: 3000 #service port
      targetPort: 3000 #containerPort in deployment.yaml
